version: '3.8'
services:
  solr:
    image: solr:8.11
    container_name: solr_instance
    ports:
      - "8983:8983"
    command: solr-precreate alunos_collection
    volumes:
      - solr_data:/var/solr
volumes:
  solr_data:
